### PR TITLE
Updated documentation in Character.java...

### PR DESCRIPTION
**Pull request by stevenpater**
- Added javadoc comments for all of the static methods in Character.java
- zero logic updates

### CODE REVIEW

**Comment by pflegera** [comment]
Excellent documentation, thanks Steve!

**Review by BluKo3 — COMMENTED** [review]
LGTM! I'll add some comments to other methods before merging

**Comment by BluKo3** [comment]
These merges are just already reviewed logic updates so I can add comments to them on this branch.

**Comment by pflegera** [comment]
Looks good to me.

**Comment by BluKo3** [comment]
More comments added, @pflegera once it passes the build can you merge to main please? The front end team doesn't need to review our PR if it is just adding comments to the backend.

**Comment by BluKo3** [comment]
She's asleep, I'm closing

**Pull request merged**
